# Django and Django REST Framework (latest) on Python 3
# Copyright (C) 2017 José Antonio López <dev@kstromeiraos.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#FROM python:3-alpine
FROM reconocimiento
#FROM ubuntu:bionic
VOLUME /dockerfilevolume
MAINTAINER José Antonio López <dev@kstromeiraos.com>

RUN apt-get update 
#RUN apt-get install python3.6 -y

#RUN python3 -m pip install --upgrade pip && \
#    pip3 install -U setuptools && \
#    pip3 install django && \
#    pip3 install djangorestframework && \
#    pip3 install markdown # Markdown support for the browsable API. \
#    && rm -rf /var/cache/apk/*
RUN python3 -m pip install --upgrade pip && rm -rf /var/cache/apk/*
#RUN apt-get install tesseract-ocr-all -y
#RUN apk add --no-cache cmake gcc libxml2 \
#       automake g++ subversion python3-dev \
#      libxml2-dev libxslt-dev lapack-dev gfortran 
#RUN apt-get install cmake gcc libxml2  automake g++ subversion python3-dev
RUN apt-get install -y  libblas-dev liblapack-dev  gfortran
RUN mkdir /app

WORKDIR /app
COPY ./app .
COPY docker-entrypoint.sh /
RUN cd /app
RUN pip3 install -r dependencias.txt
EXPOSE 8080

RUN chmod 755 /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
